filetype plugin indent on
syntax enable
set nocompatible
set undodir=~/.cache/vim/undo
set directory=~/.cache/vim/swap
set backupdir=~/.cache/vim/backup
set viminfo+=n~/.cache/vim/viminfo
set clipboard=exclude:cons\|linux autochdir
set showcmd noshowmode ruler wildmenu confirm
set nostartofline
set list listchars+=tab:├─
set tabstop=8 expandtab shiftwidth=2 softtabstop=-1 smarttab
set dictionary=/usr/share/dict/words
set keymap=vietnamese-telex imdisable iminsert=0 imsearch=-1
set omnifunc=syntaxcomplete#Complete
autocmd BufNewFile,BufRead *.PAS setlocal filetype=pascal
autocmd FileType c,h,go setlocal cindent noexpandtab shiftwidth=8
autocmd FileType rst setlocal shiftwidth=3
autocmd FileType css,javascript setlocal shiftwidth=4
autocmd BufWinEnter * let w:m1=matchadd('ColorColumn', '\%<81v.\%>80v', -1)
map Q gq
